import os
import json
import logging
import requests
from dotenv import load_dotenv

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("LearningLoop")

load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

def evaluate_and_learn(draft_reply: str, context: str) -> dict:
    """The Closed Learning Loop: The agent reviews its own draft and improves it."""
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }
    
    # The prompt forces the agent to critique itself before finalizing
    prompt = f"""
    You are an AI learning loop. Your goal is to review a drafted Reddit reply and improve it so it does not get flagged as spam.
    
    Reddit Thread Context: {context}
    Current Draft: {draft_reply}
    
    Step 1 (Analyze): Does this draft sound like a marketer wrote it? Is it too formal? 
    Step 2 (Learn): What specific words should be removed to make it sound more like a natural, casual human?
    Step 3 (Refine): Rewrite the final reply based on your learning. Keep it under 2 sentences.
    
    Return ONLY a JSON object with this exact structure:
    {{"analysis": "your analysis", "refined_reply": "the new casual reply"}}
    """
    
    data = {
        "model": "openrouter/free",
        "response_format": {"type": "json_object"},
        "messages": [{"role": "user", "content": prompt}]
    }
    
    try:
        response = requests.post(url, headers=headers, data=json.dumps(data))
        if response.status_code == 200:
            return json.loads(response.json()['choices'][0]['message']['content'])
        else:
            logger.error("Learning loop failed to connect.")
            return {"refined_reply": draft_reply}
    except Exception as e:
        logger.error(f"Error in loop: {e}")
        return {"refined_reply": draft_reply}

if __name__ == "__main__":
    logger.info("Starting Closed Learning Loop Demonstration...")
    
    # Simulating a bad, spammy draft generated by an earlier agent
    test_context = "Prediction markets are cool but the fees on Kalshi are killing my margins."
    bad_draft = "Hello valued user! I understand your pain points regarding high fees. You should transition to CrowdWisdomTrading, as our product offers superior fee structures and optimal liquidity for prediction markets."
    
    print("\n--- ORIGINAL STATE ---")
    print(f"Bad Draft: {bad_draft}")
    
    logger.info("Feeding draft into the learning loop for evaluation...")
    loop_result = evaluate_and_learn(bad_draft, test_context)
    
    print("\n--- AGENTIC LEARNING LOOP ---")
    print(f"Self-Critique: {loop_result.get('analysis')}")
    print(f"Refined Output: {loop_result.get('refined_reply')}")